# Sample workflow for building and deploying a Next.js site to GitHub Pages
#
# To get started with Next.js see: https://nextjs.org/docs/getting-started
#
name: Deploy React site to Pages

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 10.33.0
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: "24"
          cache: pnpm
      - name: Restore cache
        uses: actions/cache@v5
        with:
          path: |
            node_modules/.vite
          key: ${{ runner.os }}-vite-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-vite-pnpm-
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build with Vite
        env:
          BUILD_MODE: production
          NEXT_PUBLIC_IS_PRODUCTION_BUILD: 'true'
          NEXT_PUBLIC_BASE_PATH: 'Branding-Hackathon'
        run: pnpm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v5
        with:
          path: ./dist
      - name: List file
        run: ls -la && ls -la dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5